name: Android Release

on:
  push:
    branches:
      - feat

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.5"
          channel: "stable"

      - name: Get dependencies
        run: flutter pub get

      - name: Start release build
        run: flutter build appbundle --dart-define=APP_MODE=production

      - name: Download release build
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: build/app/outputs/bundle/release/app-release.aab
